admin_old_backup/routes/web.php
<?php
use App\User;
use App\Trip;
use App\Company;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
   // return view('welcome');
     echo "afa";
});
// Route::get('/login', function () {
//    // return view('login');
//     echo "ok";
// });
Route::get('/dashboard', function () 
{
    //$user = Session::get('user');
    $companies = Company::all();
    $drivers = User::where('user_type','driver')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->get();
     $trips = Trip::all();
    //->get();
        $data['trips'] = $trips;
     $data['companies'] = $companies;
    $data['drivers'] = $drivers;
    return view('dashboard.index')->with($data,$drivers);
})->middleware('auth');
Route::resource('admin-users', 'Admin\AdminUsersController')->middleware('auth');
Route::resource('drivers-management', 'Admin\DriversController')->middleware('auth');
Route::resource('cabs-management', 'Admin\CabsController')->middleware('auth');
Route::resource('riders-management', 'Admin\RidersController')->middleware('auth');
Route::get('trip-history-management', 'Admin\TripsController@index')->name('trip-history-management')->middleware('auth');
Route::get('reviews-management', 'Admin\ReviewsController@index')->name('reviews-management')->middleware('auth');
Route::resource('promos-management', 'Admin\PromosController')->middleware('auth'); 
Route::get('accountant-panel', 'Admin\AccountantsController@index')->name('accountant-panel')->middleware('auth');
Route::get('dispatcher-panel', 'Admin\DispatchersController@index')->name('dispatcher-panel')->middleware('auth');
Route::post('store-dispatch', 'Admin\DispatchersController@store')->name('store-dispatch')->middleware('auth');
Route::resource('company-cabs-management', 'Admin\CompanyCabsController')->middleware('auth'); 
Route::get('payments-management', 'Admin\PaymentsController@index')->name('payments-management')->middleware('auth');
Route::get('heat-map', 'Admin\HeatMapsController@index')->name('heat-map')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function() {
Route::get('/add-payment', function () {
    return view('payments.add-payment');
});
Route::post('add_payment_method', 'Admin\PaymentController@add_payment_method')->name('payment.method');

Route::post('make_payment', 'Admin\PaymentController@make_payment')->name('payment.make');

Route::get('payment-list/{trip_id}/{amount}', 'Admin\PaymentController@index')->name('payment.list');

// route for processing payment
Route::post('paypal', 'Admin\PaymentController@payWithpaypal');

// route for check status of the payment
Route::get('status', 'Admin\PaymentController@getPaymentStatus');

Route::post('order-request', 'Admin\PaymentController@save_order_request')->name('save.order');
});

admin_old_backup/app/Http/Controllers/Admin/AdminUsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use App\User;
use Illuminate\Support\Facades\Hash;
class AdminUsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $users = User::where('user_type','SuperAdministrator')->Orwhere('user_type','DispatcherAdministrator')->get();
        $data['admin_users'] = $users;
        
        return view('admin.admin-users.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return redirect('admin-users')->with('error',response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]));
        
        } 
        else 
        {
            $admin_users_exist = User::where('email',$request->email)->first();
            if($admin_users_exist)
            {
                //email already exist
                return redirect('admin-users')->with('error','Email Already Exist');

            }
            else
            {
                $admin_user = new User();
                $admin_user->name = $request->name;
                $admin_user->email = $request->email;
                $admin_user->password = Hash::make($request->password);//$request->password;
                $request->user_role = preg_replace('/\s+/', '', $request->user_role);
                //dd($request->user_role);
                $admin_user->user_type = $request->user_role;
                
                $admin_user->status = "Active";
                $admin_user->save();
                 return redirect('admin-users')->with('success','User Added successfully!');
            }
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]); 
        } 
        else 
        {
            
            
                $admin_user = User::where('id', $id)->first();
                $admin_user->name = $request->name;
                $admin_user->email = $request->email;
                //$admin_user->password = $request->password;
                $admin_user->user_type = $request->user_role;
                $admin_user->status = "Active";
                $admin_user->save();
                return redirect('admin-users')->with('success','User Updated successfully!');
                
        }
        
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

admin_old_backup/resources/views/admin/admin-users/index.blade.php
@extends('admin-layout.content')


@section('content')

	<div class="row">
		 <div class="col-lg-12">
            <div class="ibox ">

		 		<div class="ibox-content">

			 		<div class="table-responsive mt-3">
			 		
				 			<div class="col-12">
				 				<h2 class="font-weight-bold float-left">Admin supervision</h2>
				 			</div>
				 			<div>
                                @include('../../admin-layout/flash-message')
							</div>
				 			<div class="col-12 ">
				 				<button data-toggle="modal" 
   									data-target="#adminModal" class="btn btn-success float-right">Add Admin</button>
					 			<button class="btn btn-default float-right mr-5">Export</button>
					 			
				 			</div>
			 			
			 			<div class="clearfix"></div>
			 			<table class="table table-striped  table-hover dataTables-admin" >
			 				<thead>
			 					<tr>
			 						<th>ID</th>
			 						<th>Admin name</th>
			 						<th>Email</th>
			 						<th>Roles</th>
			 						<th>Status</th>
			 						<th></th>
			 						<th></th>
			 					</tr>
			 				</thead>
			 				<tbody>
			 				    @foreach ($admin_users as $admin_user)
			 					<tr class="gradeX">
			 						<td class="center">{{$admin_user->id}}</td>
			 						<td class="center">{{$admin_user->name}}</td>
			 						<td class="center">{{$admin_user->email}}</td>
			 						<td class="center">{{$admin_user->user_type}}</td>
			 						<td class="center"><span class="label label-primary">{{$admin_user->status}}</span></td>
			 						<td class="center"><i class="fas fa-pen" data-toggle="modal" data-target="#adminEditModal" onClick="return userInfo({{$admin_user}})" ></i></td>
			 						<td class="center"><i class="fa fa-times"></i></td>
			 					</tr>
			 				</tbody>
			 				    @endforeach
			 			</table>
			 			
			 			
			 		</div>
		 		</div>
		 	</div>
		</div>
	</div>


	<div class="modal fade" id="adminModal" 
			tabindex="-1" role="dialog" 
			aria-labelledby="adminModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" 
				id="adminModalLabel">Add new Admin</h4>
			</div>
			<div class="modal-body">
										<div class="col-md-12">

							<!--begin::Portlet-->
							<div class="kt-portlet">
														
								<!--begin::Form-->
								<form  action="{{route('admin-users.store')}}" method="post" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
									{{csrf_field()}}
									<div class="kt-portlet__body">
										<div class="form-group form-inline">
											<label class="col-md-3 col-form-label">Name:</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter full name" name="name">
										</div>
										<div class="form-group form-inline">
											<label class="col-md-3 col-form-label" for="sel1">Select Role:</label>
											<select name="user_role" class="col-md-7 form-control" id="sel1">
												<option>Super Administrator</option>
												<option>Dispatcher Administrator</option>
											</select>
										</div>
										<div class="form-group form-inline">
											<label class="col-md-3 col-form-label">Email:</label>
											<input type="email" class="col-md-7 form-control" placeholder="Enter Email Address" name="email">
										</div>
										<div class="form-group form-inline">
											<label class="col-md-3 col-form-label">Password:</label>
											<input type="password" class="col-md-7 form-control" placeholder="Enter Password" name="password">
										</div>
									</div>
									<div class="kt-portlet__foot">
										<div class="kt-form__actions text-center">
											<input type="submit" value="Save" class="btn btn-primary"/> 
											<button type="button" 
										class="btn btn-default" 
										data-dismiss="modal">Close</button>
										</div>
									</div>
								</form>

								<!--end::Form-->
							</div>
							</div>

			</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
			</div>
		</div>
		</div>


<!--Edit-->
		<div class="modal fade" id="adminEditModal" 
			tabindex="-1" role="dialog" 
			aria-labelledby="adminEditModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" 
				id="adminEditModalLabel">Edit Admin User</h4>
			</div>
			<div class="modal-body">
										<div class="col-md-12">

							<!--begin::Portlet-->
							<div class="kt-portlet">
								<!--begin::Form-->
								<form id="update_form"  method="POST" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
									{{csrf_field()}}
									{{ method_field('PUT') }}
									<input type="hidden" name="id" id="id">
    								<!-- <input type="hidden" name="_token" value="{{ csrf_token() }}"> -->
									<div class="kt-portlet__body">
										<div class="form-group">
											<label>Name:</label>
											<input type="text" class="form-control" placeholder="Enter full name" name="name" id="name">
										</div>
										<div class="form-group">
											<label for="user_role">Select Role:</label>
											
											<select name="user_role" class="form-control" id="user_role">
												<!-- <option>Logixcess</option>
												<option>NetSol</option>
												<option>Systems Limited</option>
												<option>ArbiSoft</option> -->
												<option>Super Administrator</option>
												<option>Dispatcher Administrator</option>
											
												
											</select>
										</div>
										<div class="form-group">
											<label>Email:</label>
											<input type="email" class="form-control" placeholder="Enter Email Address" name="email" id="email">
										</div>
										<div class="form-group">
											<label>Password:</label>
											<input type="password" class="form-control" placeholder="Enter Password" name="password" id="password">
										</div>
									
									</div>
									<div class="kt-portlet__foot">
										<div class="kt-form__actions">
											<input type="submit" value="Update" class="btn btn-primary"/> 
											<button type="button" 
										class="btn btn-default" 
										data-dismiss="modal">Close</button>
										</div>
									</div>
								</form>

								<!--end::Form-->
							</div>
							</div>

			</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
			</div>
		</div>
		</div>




 @endsection
 @section('script-dashboard')

 <script>
        $(document).ready(function(){
            $('.dataTables-admin').DataTable({
            	"lengthChange": false,
            	"searching": false,
            	"bInfo" : false,
            	"bSort" : false,

                responsive: true,
               
				language: {
					paginate: {
						next: '<i class="fas fa-angle-right fa-lg"></i>',
						previous: '<i class="fas fa-angle-left fa-lg"></i>'  
					}
				}

            });

        });
        
        
        function userInfo(data){
          $('.modal-title').html('Edit Admin User');
          $("#name").val(data.name);
          $("#email").val(data.email);
          $("#password").val(data.password);
		  $('#user_role').val(data.user_type);
		  $('#id').val(data.id);
		  
		  var url = '{{ route("admin-users.update", ":slug") }}';
		  url = url.replace(':slug', data.id);
		  $('#update_form').attr('action', url);
		  
		  
		  $('#adminEditModal').modal('show');
      }

    </script>
 @stop