routes/web.php
<?php
use App\User;
use App\Trip;
use App\Company;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// $a = Crypt::encrypt('MobileGoEncyptionKey@BBIF322#4@3234637867663352');

// echo $a; die;
Auth::routes();

Route::get('/', function () {
    return view('welcome');
    // echo "afa";
});
// Route::get('/login', function () {
//    // return view('login');
//     echo "ok";
// });
Route::get('/dashboard', function () 
{
    //$user = Session::get('user');
    $companies = Company::all();
    $drivers = User::where('user_type','driver')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->get();
    $completed = Trip::where('trip_status','completed')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->count();
    $cancelled = Trip::where('trip_status','cancelled')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->count();

    $active = User::where('user_type','driver')->where("status","Active")//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->count();
    $Inactive = User::where('user_type','driver')->where("status","InActive")//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->count();

  
     $trips = Trip::all();
    //->get();
        $data['trips'] = $trips;
     $data['companies'] = $companies;
    $data['drivers'] = $drivers;
    $data['completed'] = $completed;
    $data['active'] = $active;
    $data['Inactive'] = $Inactive;
    $data['cancelled'] = $cancelled;
    return view('dashboard.index')->with($data,$drivers);
})->middleware('auth');

Route::resource('admin-users', 'Admin\AdminUsersController')->middleware('auth');
Route::resource('drivers-management', 'Admin\DriversController')->middleware('auth');
Route::resource('cabs-management', 'Admin\CabsController')->middleware('auth');
Route::resource('riders-management', 'Admin\RidersController')->middleware('auth');
Route::get('trip-history-management', 'Admin\TripsController@index')->name('trip-history-management')->middleware('auth');
Route::get('reviews-management', 'Admin\ReviewsController@index')->name('reviews-management')->middleware('auth');
Route::resource('promos-management', 'Admin\PromosController')->middleware('auth'); 
Route::get('accountant-panel', 'Admin\AccountantsController@index')->name('accountant-panel')->middleware('auth');
Route::get('dispatcher-panel', 'Admin\DispatchersController@index')->name('dispatcher-panel')->middleware('auth');
Route::post('store-dispatch', 'Admin\DispatchersController@store')->name('store-dispatch')->middleware('auth');
Route::resource('company-cabs-management', 'Admin\CompanyCabsController')->middleware('auth'); 
Route::get('payments-management', 'Admin\PaymentsController@index')->name('payments-management')->middleware('auth');
Route::get('heat-map', 'Admin\HeatMapsController@index')->name('heat-map')->middleware('auth');
Route::resource('cabs-model-management', 'Admin\CabModelsController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function() {
Route::get('/add-payment', function () {
    return view('payments.add-payment');
});
Route::post('add_payment_method', 'Admin\PaymentController@add_payment_method')->name('payment.method');

Route::post('make_payment', 'Admin\PaymentController@make_payment')->name('payment.make');

Route::get('payment-list/{trip_id}/{amount}', 'Admin\PaymentController@index')->name('payment.list');

// route for processing payment
Route::post('paypal', 'Admin\PaymentController@payWithpaypal');

// route for check status of the payment
Route::get('status', 'Admin\PaymentController@getPaymentStatus');

Route::post('order-request', 'Admin\PaymentController@save_order_request')->name('save.order');


// Trip Controller


Route::get('trip-invoice/{id}', 'Admin\TripsController@tripInvoice');


// Cab Service Controller 
Route::get('cab-service', 'Admin\CabServiceController@index');


// Rider Controller
Route::get('rider-history/{id}', 'Admin\RidersController@history');



});

app/Http/Controllers/Admin/DriversController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Company;
use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Facades\Hash;
use Session;
use Illuminate\Support\Facades\Redirect;
class DriversController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        $drivers = User::where('user_type','driver')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->get();
        //dd($companies[0]->company_name);
        //dd($drivers[0]->company->company_name);
        $data['companies'] = $companies;
        $data['drivers'] = $drivers;
        return view('admin.drivers.index')->with($data,$drivers);//,$companies);//compact(['companies' => $companies]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.drivers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'phone' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return redirect('drivers-management')->with('error',response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]));
        
            // return response()->json([
            //     'type' =>'error',
            //     'msg' => $validator->getMessageBag ()->toArray(),
            // ]); 
        } else {
            
            // if ($request->hasFile('image_url')) {
            // $filenameWithExt = $request->file('image_url')->getClientOriginalName();
            // $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // $extension = $request->file('image_url')->getClientOriginalExtension();
            // $filenameToStore = $filename . '_' . time() . '.' . $extension;
            // $path = $request->file('image_url')->move('images/job_categories', $filenameToStore);
        	// } else {
            // $filenameToStore = 'noimage.jpg';
        	// }
            $company_exist = Company::where('company_name',$request->company)->first();
            if($company_exist)
            {
                $driver = new User();
                $driver->name = $request->name;
                $driver->email = $request->email;
                //$driver->image_url = $path;//$filenameToStore;
                $driver->phone_no = $request->phone;
                $driver->fk_company_id = $company_exist->id;
                $driver->user_type = "driver";
                $driver->password = Hash::make($request->password);
                $driver->status = "Active";
                $driver->save();
             return redirect('drivers-management')->with('success','Driver Added successfully!');
                
            }
            else
            {
                return redirect('drivers-management')->with('error','Company Not Found!');
            }
            
        }   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //dd($id);
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'phone' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]); 
        } 
        else 
        {
             $company_exist = Company::where('company_name',$request->company)->first();
            // if($company_exist)
            // {
                $driver  = User::where('id', $id)->first();
                $driver->name = $request->name;
                $driver->email = $request->email;
                $driver->phone_no = $request->phone;
                $driver->fk_company_id = ($company_exist )  ? $company_exist->id : NULL;
                //->where('destination', 'San Diego')
                //User::where('id', $request->input('id'))
                //->update($driver);
                $driver->save();
                return redirect('drivers-management')->with('success','Driver Updated successfully!');
                //->update(['delayed' => 1]);
            // }
            // else
            // {
            //    return redirect('drivers-management')->with('error','Company Not Found!');
            // }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $exist = User::where('id',$id)->first();
        if($exist)
        {
            $exist->delete();
            return redirect('drivers-management')->with('success','Driver Deleted successfully!');
        }
        else
        {
            return redirect('drivers-management')->with('error','Driver Not Found!');
        }
    }
}

resources/views/admin/drivers/create.blade.php
@extends('admin-layout.content')

@section('sidebar')



@section('content')

<div class="col-md-12">

    <!--begin::Portlet-->
    <div class="kt-portlet">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Add Driver
                </h3>
            </div>
        </div>
                                   
        <!--begin::Form-->
        <form  action="{{route('drivers-management.store')}}" method="post" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
            {{csrf_field()}}
            <div class="kt-portlet__body">
                <div class="form-group">
                    <label>Name:</label>
                    <input type="text" class="form-control" placeholder="Enter full name" name="name">
                </div>
                <div class="form-group">
                    <label for="sel1">Select Company:</label>
                    <select class="form-control" id="sel1">
                        <option>Logixcess</option>
                        <option>NetSol</option>
                        <option>Systems Limited</option>
                        <option>ArbiSoft</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Email:</label>
                    <input type="email" class="form-control" placeholder="Enter Email Address" name="email">
                </div>
                <div class="form-group">
                    <label>Phone Number:</label>
                    <input type="text" class="form-control" placeholder="Enter Phone Number" name="phone">
                </div>
                <!-- <div class="form-group">
						<label>Job Category Image</label>
						<input type="file" class="form-control form-control-line" name="image_url" required="required"> 
						
					</div> -->
            </div>
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <input type="submit" value="Submit" class="btn btn-primary"/> 
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>
</div>

<!--end::Portlet-->

<!--begin::Portlet-->




@endsection
@section('script-dashboard')

 <script>
        $(document).ready(function(){
            $('.dataTables-admin').DataTable({
            	"lengthChange": false,
            	"searching": false,
            	"bInfo" : false,
            	"bSort" : false,

                responsive: true,
               
				language: {
					paginate: {
						next: '<i class="fas fa-angle-right fa-lg"></i>',
						previous: '<i class="fas fa-angle-left fa-lg"></i>'  
					}
				}

            });

        });

    </script>
 @stop

resources/views/admin/drivers/index.blade.php
@extends('admin-layout.content')


@section('content')

<div class="row">
	<div class="col-lg-12">
		<div class="ibox ">

			<div class="ibox-content">

				<div class="table-responsive mt-3">

					<div class="col-12">
						<h2 class="font-weight-bold float-left">Driver Mangement</h2>
					</div>
					<div>
						@include('../../admin-layout/flash-message')
					</div>
					<div class="col-12 ">
						<button data-toggle="modal" 
						data-target="#driversModal" class="btn btn-success float-right">Add Driver
					</button> 
				<!-- 	<a href="{{route('drivers-management.create')}}" class="btn btn-success float-right">
						<i class="la la-plus"></i>
								Add Driver
								</a> -->
							<!-- 	<select class="btn btn-default float-right mr-5">
									<option>Options</option>
								</select>
 -->
								<button class="btn btn-default float-right mr-5">Export</button>

								
							</div>

							<div class="clearfix"></div>
							<table class="table table-striped  table-hover dataTables-admin" >
								<thead>
									<tr>
										<th>Name</th>
										<th>Company Name</th>
										<th>Email</th>
										<th>Phone number</th>
										<th>Sign up date</th>
										<th>Wallet balance</th>
										<th>Cab count</th>
										<th>Status</th>
										<th></th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									@foreach ($drivers as $driver)
									<tr class="gradeX">
										<td class="center">{{$driver->name}}</td>
										<td class="center">
											@if(is_null($driver->company))
											{{ 'Empty' }} 
											@else
											{{ $driver->company->company_name }}
											@endif
										</td>
										<td class="center">{{$driver->email}}</td>
										<td class="center">{{$driver->phone_no}}</td>
										<td class="center">{{$driver->created_at}}</td>
										<td class="center">0</td>
										<td class="center">1</td>
										<td class="center"><span class="label label-primary">{{$driver->status}}</span></td>
										<td class="center"><i class="fas fa-pen" data-toggle="modal" data-target="#driversEditModal" onClick="return driverInfo({{$driver}})">
										</i> 
									</td>
									<td class="center"><i class="fa fa-times" data-toggle="modal" data-target="#deleteModal" onClick="return deleteDriver({{$driver->id}})"></i></td>
								</tr>
								@endforeach
							</tbody>
						</table>


					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="driversModal" 
	tabindex="-1" role="dialog" 
	aria-labelledby="driversModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" 
				id="driversModalLabel">Add Driver</h4>
			</div>
			<div class="modal-body">
				<div class="col-md-12">

					<!--begin::Portlet-->
					<div class="kt-portlet">

						<!--begin::Form-->
						<form  action="{{route('drivers-management.store')}}" method="post" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
							{{csrf_field()}}
							<div class="kt-portlet__body">
								<div class="form-group">
									<label>Name:</label>
									<input type="text" class="form-control" placeholder="Enter full name" name="name">
								</div>
								<div class="form-group">
									<label for="sel1">Select Company:</label>

									<select name="company" class="form-control" id="sel1">
												<!-- <option>Logixcess</option>
												<option>NetSol</option>
												<option>Systems Limited</option>
												<option>ArbiSoft</option> -->
												<option value="">Select Company</option>
												@foreach ($companies as $company)

												<option>{{$company->company_name}}</option>
												@endforeach

												
											</select>
										</div>
										<div class="form-group">
											<label>Email:</label>
											<input type="email" class="form-control" placeholder="Enter Email Address" name="email">
										</div>
										<div class="form-group">
											<label>Password:</label>
											<input type="password" class="form-control" placeholder="Enter Password" name="password">
										</div>
										<div class="form-group">
											<label>Phone Number:</label>
											<input type="text" class="form-control" placeholder="Enter Phone Number" name="phone">
										</div>
									</div>
									<div class="kt-portlet__foot">
										<div class="kt-form__actions">
											<input type="submit" value="Save" class="btn btn-primary"/> 
											<button type="button" 
											class="btn btn-default" 
											data-dismiss="modal">Close</button>
										</div>
									</div>
								</form>

								<!--end::Form-->
							</div>
						</div>

					</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
		</div>
	</div>
</div>



<!--Edit-->
<div class="modal fade" id="driversEditModal" 
tabindex="-1" role="dialog" 
aria-labelledby="driversEditModalLabel">
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title" 
			id="driversEditModalLabel">Edit Driver</h4>
		</div>
		<div class="modal-body">
			<div class="col-md-12">

				<!--begin::Portlet-->
				<div class="kt-portlet">
					<!--route('drivers-management.update_driver  -->
					<!--begin::Form-->
					<form id="update_form"  method="POST" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
						{{csrf_field()}}
						@method('PUT')
						<input type="hidden" name="id" id="id">
						<!-- <input type="hidden" name="_token" value="{{ csrf_token() }}"> -->
						<div class="kt-portlet__body">
							<div class="form-group">
								<label>Name:</label>
								<input type="text" class="form-control" placeholder="Enter full name" name="name" id="name">
							</div>
							<div class="form-group">
								<label for="sel1">Select Company:</label>

								<select name="company" class="form-control" id="company">
												<!-- <option>Logixcess</option>
												<option>NetSol</option>
												<option>Systems Limited</option>
												<option>ArbiSoft</option> -->
												<option value="">Select Company</option>
												@foreach ($companies as $company)
												<option>{{$company->company_name}}</option>
												@endforeach

												
											</select>
										</div>
										<div class="form-group">
											<label>Email:</label>
											<input type="email" class="form-control" placeholder="Enter Email Address" name="email" id="email">
										</div>
										<div class="form-group">
											<label>Password:</label>
											<input type="password" class="form-control" placeholder="Enter Password" name="password" id="password">
										</div>
										<div class="form-group">
											<label>Phone Number:</label>
											<input type="text" class="form-control" placeholder="Enter Phone Number" name="phone" id="phone">
										</div>
									</div>
									<div class="kt-portlet__foot">
										<div class="kt-form__actions">
											<input type="submit" value="Update" class="btn btn-primary"/> 
											<button type="button" 
											class="btn btn-default" 
											data-dismiss="modal">Close</button>
										</div>
									</div>
								</form>

								<!--end::Form-->
							</div>
						</div>

					</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
		</div>
	</div>
</div>



<!-- Delete Modal -->
<!-- Modal HTML -->
<div id="deleteModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<!-- <div class="icon-box">
					<i class="glyphicon glyphicon-trash"></i>
				</div>				 -->
				<h2 class="modal-title">Are you sure ?</h4>	
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<input type="hidden" class="form-control" name="input_del" id="input_del">
					<p>Do you really want to delete these records? This process cannot be undone.</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
					<!-- action="{{ route('drivers-management.destroy', 2) }}" -->
					<form id="delete_form"  method="POST">
						{{ method_field('DELETE') }}
						{{ csrf_field() }}
						<!-- {{ csrf_field() }} -->
						<input type="submit" value="Delete" class="btn btn-danger btn-block">
					</form>

					<!-- <a href="{{ URL::to('drivers-management/' . '2') }}" class="btn btn-danger">Delete</a> -->

					<!-- <button href="{{ route('drivers-management.destroy',1) }}" type="button" class="btn btn-danger">Delete</button> -->
				</div>
			</div>
		</div>


		@endsection
		@section('script-dashboard')

		<script>
			$(document).ready(function(){
				$('.dataTables-admin').DataTable({
					"lengthChange": false,
					"searching": false,
					"bInfo" : false,
					"bSort" : false,

					responsive: true,

					language: {
						paginate: {
							next: '<i class="fas fa-angle-right fa-lg"></i>',
							previous: '<i class="fas fa-angle-left fa-lg"></i>'  
						}
					}

				});

			});

			function driverInfo(data){

				//console.log(data);
				$('.modal-title').html('Edit Driver');
				$("#name").val(data.name);
				$("#email").val(data.email);
				$("#password").val(data.password);
				$('#phone').val(data.phone_no);
				$('#id').val(data.id);
				if(data.fk_company_id != null){
				$('#company').val(data.company.company_name);
				}

				var url = '{{ route("drivers-management.update", ":slug") }}';
				url = url.replace(':slug', data.id);
				$('#update_form').attr('action', url);


				$('#driversEditModal').modal('show');
			}
			function deleteDriver(slug){
				$('#input_del').val(slug);
				var url = '{{ route("drivers-management.destroy", ":slug") }}';
				url = url.replace(':slug', slug);
				$('#delete_form').attr('action', url);
				$('#deleteModal').modal('show');
			}
		</script>
		@stop