admin_old_backup/routes/web.php
<?php
use App\User;
use App\Trip;
use App\Company;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
   // return view('welcome');
     echo "afa";
});
// Route::get('/login', function () {
//    // return view('login');
//     echo "ok";
// });
Route::get('/dashboard', function () 
{
    //$user = Session::get('user');
    $companies = Company::all();
    $drivers = User::where('user_type','driver')//->with(['company' => function ($query) {$query->select(['company_name']);}])
    ->get();
     $trips = Trip::all();
    //->get();
        $data['trips'] = $trips;
     $data['companies'] = $companies;
    $data['drivers'] = $drivers;
    return view('dashboard.index')->with($data,$drivers);
})->middleware('auth');
Route::resource('admin-users', 'Admin\AdminUsersController')->middleware('auth');
Route::resource('drivers-management', 'Admin\DriversController')->middleware('auth');
Route::resource('cabs-management', 'Admin\CabsController')->middleware('auth');
Route::resource('riders-management', 'Admin\RidersController')->middleware('auth');
Route::get('trip-history-management', 'Admin\TripsController@index')->name('trip-history-management')->middleware('auth');
Route::get('reviews-management', 'Admin\ReviewsController@index')->name('reviews-management')->middleware('auth');
Route::resource('promos-management', 'Admin\PromosController')->middleware('auth'); 
Route::get('accountant-panel', 'Admin\AccountantsController@index')->name('accountant-panel')->middleware('auth');
Route::get('dispatcher-panel', 'Admin\DispatchersController@index')->name('dispatcher-panel')->middleware('auth');
Route::post('store-dispatch', 'Admin\DispatchersController@store')->name('store-dispatch')->middleware('auth');
Route::resource('company-cabs-management', 'Admin\CompanyCabsController')->middleware('auth'); 
Route::get('payments-management', 'Admin\PaymentsController@index')->name('payments-management')->middleware('auth');
Route::get('heat-map', 'Admin\HeatMapsController@index')->name('heat-map')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function() {
Route::get('/add-payment', function () {
    return view('payments.add-payment');
});
Route::post('add_payment_method', 'Admin\PaymentController@add_payment_method')->name('payment.method');

Route::post('make_payment', 'Admin\PaymentController@make_payment')->name('payment.make');

Route::get('payment-list/{trip_id}/{amount}', 'Admin\PaymentController@index')->name('payment.list');

// route for processing payment
Route::post('paypal', 'Admin\PaymentController@payWithpaypal');

// route for check status of the payment
Route::get('status', 'Admin\PaymentController@getPaymentStatus');

Route::post('order-request', 'Admin\PaymentController@save_order_request')->name('save.order');
});

admin_old_backup/app/Promo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promo extends Model
{
    //
}

admin_old_backup/app/Http/Controllers/Admin/PromosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Promo;
use Validator;
class PromosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $promos = Promo::all();
        //dd($companies[0]->company_name);
        //dd($drivers[0]->company->company_name);
        $data['promos'] = $promos;
       
        return view('admin.promos.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'promo_code' => 'required',
            'user_type' => 'required',
            'discount_type' => 'required',
            'usage_count' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return redirect('promos-management')->with('error',response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]));
        
             
        } else {
            
            // if ($request->hasFile('image_url')) {
            // $filenameWithExt = $request->file('image_url')->getClientOriginalName();
            // $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // $extension = $request->file('image_url')->getClientOriginalExtension();
            // $filenameToStore = $filename . '_' . time() . '.' . $extension;
            // $path = $request->file('image_url')->move('images/job_categories', $filenameToStore);
        	// } else {
            // $filenameToStore = 'noimage.jpg';
        	// }
                $promo = new Promo();
                $promo->promo_code = $request->promo_code;
                $promo->user_type = $request->user_type;
                $promo->discount_type = $request->discount_type;
                $promo->expiry_date = $request->expiry_date;
                $promo->usage_count = $request->usage_count;
                $promo->status = "enable";
                $promo->save();
             return redirect('promos-management')->with('success','Promo Added successfully!');            
        }   

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $validator = Validator::make($request->all(), [
            'promo_code' => 'required',
            'user_type' => 'required',
            'discount_type' => 'required',
            'usage_count' => 'required',
        ]);
        if ($validator->fails()) 
        {
            return redirect('promos-management')->with('error',response()->json([
                'type' =>'error',
                'msg' => $validator->getMessageBag ()->toArray(),
            ]));
           
        } else {
            
            $promo_exist = Promo::where('id',$request->id)->first();
            if($promo_exist)
            {
                $promo  = Promo::where('id',$request->id)->first();
                $promo->promo_code = $request->promo_code;
                $promo->user_type = $request->user_type;
                $promo->discount_type = $request->discount_type;
                $promo->expiry_date = $request->expiry_date;
                $promo->usage_count = $request->usage_count;
                $promo->save();
             return redirect('promos-management')->with('success','Promo Updated successfully!');
            }
            else
            {
                return redirect('promos-management')->with('error','Promo Not Found!');
            }
                            
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $exist = Promo::where('id',$id)->first();
        if($exist)
        {
            $exist->delete();
            return redirect('promos-management')->with('success','Promo Deleted successfully!');
        }
        else
        {
            return redirect('promos-management')->with('error','Promo Not Found!');
        }
    }
}

admin_old_backup/resources/views/admin/promos/index.blade.php
@extends('admin-layout.content')


@section('content')

	<div class="row">
		 <div class="col-lg-12">
            <div class="ibox ">

		 		<div class="ibox-content">

			 		<div class="table-responsive mt-3">
			 		
				 			<div class="col-12">
				 				<h2 class="font-weight-bold float-left">Promo Mangement</h2>
				 			</div>
							 <div>
                                @include('../../admin-layout/flash-message')
							</div>
				 			<div class="col-12 ">
				 				<button data-toggle="modal" 
   									data-target="#promosModal" class="btn btn-success float-right">Create new promo code</button>
					 			<button class="btn btn-default float-right mr-5">Export</button>
					 			
				 			</div>
			 			
			 			<div class="clearfix"></div>
			 			<table class="table table-striped  table-hover dataTables-admin" >
			 				<thead>
			 					<tr>
			 						<th>#</th>
			 						<th>Promo Code</th>
			 						<th>User Type</th>
			 						<th>Discount Type</th>
			 						<th>Usage Count</th>
			 						<th>Experiation</th>
			 						<th>Status</th>
			 						<th>Action</th>
			 					
			 					</tr>
			 				</thead>
			 				<tbody>
							@foreach ($promos as $promo)
			 					<tr class="gradeX">
			 						<td class="center">{{$promo->id}}</td>
			 						<td class="center">{{$promo->promo_code}}</td>
			 						<td class="center">{{$promo->user_type}}</td>
			 						<td class="center">{{$promo->discount_type}}</td>
			 						<td class="center">{{$promo->usage_count}}</td>
			 						<td class="center">{{$promo->expiry_date}}</td>
			 						<td><span class="label label-primary">Enable</span>
			 							<span class="label">Disable</span>
			 						</td>
			 						<td><i class="fas fa-pen" data-toggle="modal" data-target="#promosEditModal" onClick="return promoInfo({{$promo}})"></i>
			 							<i class="fa fa-times" data-toggle="modal" data-target="#deleteModal" onClick="return deletePromo({{$promo->id}})"></i>
			 						</td>
			 					</tr>
							@endforeach
			 				</tbody>
			 			</table>
			 			
			 			
			 		</div>
		 		</div>
		 	</div>
		</div>
	</div>


	<div class="modal fade" id="promosModal" 
			tabindex="-1" role="dialog" 
			aria-labelledby="promosModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header text-center">
				<h4 class="modal-title text-center justify-content-center" 
				id="promosModalLabel">Add new Promo Code</h4>
			</div>
			<div class="modal-body">
										<div class="col-md-12">

							<!--begin::Portlet-->
							<div class="kt-portlet">
														
								<!--begin::Form-->
								<form  action="{{route('promos-management.store')}}" method="post" enctype="multipart/form-data" class="kt-form ajax-form" data-cb="job_category_add"><!-- Form row -->
									{{csrf_field()}}
									<div class="kt-portlet__body">
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">PromoCode:</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter promo code" name="promo_code">
										</div>
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label" for="sel1">Discount Type</label>
											<select class="col-md-7 form-control" name="discount_type" id="sel1">
												<option>Full</option>
												<option>Half</option>
												<option>20%</option>
												<option>10%</option>
											</select>
										</div>
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label" for="sel2">User Type</label>
											<select class="col-md-7 form-control" name="user_type" id="sel2">
												<option>Super</option>
												<option>Regular</option>
												<option>Normal</option>
											</select>
										</div>
										<!-- <div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Starting at</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter starting price" name="start_price">
										</div> -->
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Usage Count</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter usage count" name="usage_count">
										</div>
										<!-- <div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Discount</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter Discount" name="discount">
										</div> -->
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Expiry Date</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter Expiry Date" name="expiry_date">
										</div>
									</div>
									<div class="kt-portlet__foot text-center">
										<div class="kt-form__actions text-center">
											<input type="submit" value="Submit" class="btn btn-primary"/> 
											<button type="button" 
										class="btn btn-default" 
										data-dismiss="modal">Close</button>
										</div>
										
									</div>
								</form>

								<!--end::Form-->
							</div>
							</div>

			</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
			</div>
		</div>
		</div>



	<!-- Edit Promo-->

		<!--Edit-->
		<div class="modal fade" id="promosEditModal" 
			tabindex="-1" role="dialog" 
			aria-labelledby="promosEditModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" 
				id="promosEditModalLabel">Edit Promo</h4>
			</div>
			<div class="modal-body">
										<div class="col-md-12">

							<!--begin::Portlet-->
							<div class="kt-portlet">
														<!--route('drivers-management.update_driver  -->
								<!--begin::Form-->
								<form id="update_form"  method="POST" enctype="multipart/form-data" class="kt-form ajax-form"><!-- Form row -->
									{{csrf_field()}}
									{{ method_field('PUT') }}
									<input type="hidden" name="id" id="id">
									<div class="kt-portlet__body">
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">PromoCode:</label>
											<input id="promo_code" type="text" class="col-md-7 form-control" placeholder="Enter promo code" name="promo_code">
										</div>
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label" for="discount_type">Discount Type</label>
											<select class="col-md-7 form-control" name="discount_type" id="discount_type">
												<option>Full</option>
												<option>Half</option>
												<option>20%</option>
												<option>10%</option>
											</select>
										</div>
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label" for="user_type">User Type</label>
											<select class="col-md-7 form-control" name="user_type" id="user_type">
												<option>Super</option>
												<option>Regular</option>
												<option>Normal</option>
											</select>
										</div>
										<!-- <div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Starting at</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter starting price" name="start_price">
										</div> -->
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Usage Count</label>
											<input type="text" class="col-md-7 form-control" id="usage_count" placeholder="Enter usage count" name="usage_count">
										</div>
										<!-- <div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Discount</label>
											<input type="text" class="col-md-7 form-control" placeholder="Enter Discount" name="discount">
										</div> -->
										<div class="form-group form-inline">
											<label class="col-md-4 col-form-label">Expiration</label>
											<input type="text" id="expiry_date" class="col-md-7 form-control" placeholder="Enter Expiration" name="expiry_date">
										</div>
									</div>
									<div class="kt-portlet__foot text-center">
										<div class="kt-form__actions text-center">
											<input type="submit" value="Update" class="btn btn-primary"/> 
											<button type="button" 
										class="btn btn-default" 
										data-dismiss="modal">Close</button>
										</div>
										
									</div>
								</form>
								<!--end::Form-->
							</div>
							</div>

			</div>
			<!-- <div class="modal-footer">
				<button type="button" 
				class="btn btn-default" 
				data-dismiss="modal">Close</button>
				<span class="pull-right">
				<button type="button" class="btn btn-primary">
					Save
				</button>
				</span>
			</div> -->
			</div>
		</div>
		</div>


	<!-- Delete Modal -->
<!-- Modal HTML -->
<div id="deleteModal" class="modal fade">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<!-- <div class="icon-box">
					<i class="glyphicon glyphicon-trash"></i>
				</div>				 -->
				<h2 class="modal-title">Are you sure ?</h4>	
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			</div>
			<div class="modal-body">
			<input type="hidden" class="form-control" name="input_del" id="input_del">
				<p>Do you really want to delete these records? This process cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
				<form id="delete_form"  method="POST">
   				{{ method_field('DELETE') }}
				   {{ csrf_field() }}
   				<!-- {{ csrf_field() }} -->
   				<input type="submit" value="Delete" class="btn btn-danger btn-block">
				</form>

				<!-- <a href="{{ URL::to('drivers-management/' . '2') }}" class="btn btn-danger">Delete</a> -->
				
				<!-- <button href="{{ route('drivers-management.destroy',1) }}" type="button" class="btn btn-danger">Delete</button> -->
			</div>
		</div>
	</div>
 @endsection
 @section('script-dashboard')

 <script>
        $(document).ready(function(){
            $('.dataTables-admin').DataTable({
            	"lengthChange": false,
            	"searching": false,
            	"bInfo" : false,
            	"bSort" : false,

                responsive: true,
               
				language: {
					paginate: {
						next: '<i class="fas fa-angle-right fa-lg"></i>',
						previous: '<i class="fas fa-angle-left fa-lg"></i>'  
					}
				}

            });

        });

	function promoInfo(data){
          $('.modal-title').html('Edit Promo');
          $("#promo_code").val(data.promo_code);
          $("#user_type").val(data.user_type);
          $("#discount_type").val(data.discount_type);
		  $('#expiry_date').val(data.expiry_date);
		  $('#usage_count').val(data.usage_count);
		  $('#id').val(data.id);
		  
		  var url = '{{ route("promos-management.update", ":slug") }}';
		  url = url.replace(':slug', data.id);
		  $('#update_form').attr('action', url);
		  
		  
		  $('#promosEditModal').modal('show');
      }
	  function deletePromo(slug){
		$('.modal-title').html('Delete Promo');
          $('#input_del').val(slug);
		  var url = '{{ route("promos-management.destroy", ":slug") }}';
		  url = url.replace(':slug', slug);
		  $('#delete_form').attr('action', url);
		  $('#deleteModal').modal('show');
      }

    </script>
 @stop